eCommerceSite/Controllers/CartController.cs
using eCommerceSite.Data;
using eCommerceSite.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eCommerceSite.Controllers
{
    public class CartController : Controller
    {
        private readonly ProductContext _context;
        private readonly IHttpContextAccessor _httpContext;
        public CartController(ProductContext context, IHttpContextAccessor httpContext)
        {
            _context = context;
            _httpContext = httpContext;
        }

        /// <summary>
        /// Add a product to the shopping cart
        /// </summary>
        /// <param name="id">The Id of the product to add</param>
        /// <returns></returns>
        public async Task<IActionResult> Add(int id, string prevUrl)
        {
            Product p = await ProductDB.GetSingleProductAsync(_context, id);

            // Add current product to exsisting cart
            CookieHelper.AddProductToCart(_httpContext, p);
            TempData["Message"] = $"{p.Title} added successfully to your cart.";

            // redirect to preivious page
            return Redirect(prevUrl);
        }

        public IActionResult Summary()
        {
            // Display all products in the shopping cart cookie
            List<Product> cartProducts = CookieHelper.GetCartProducts(_httpContext);
            return View(cartProducts);
        }
    }
}

eCommerceSite/Controllers/ProductController.cs
using eCommerceSite.Data;
using eCommerceSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eCommerceSite.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductContext _context;

        public ProductController(ProductContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Displays a view that lists a page of products
        /// </summary>
        public async Task<IActionResult> Index(int? id)
        {
            // can be condensed further! int pageNum = id ?? 1; null coalesing operator ??
            int pageNum = id.HasValue ? id.Value : 1; // if else ternary operator
            const int PageSize = 3;
            ViewData["CurrentPage"] = pageNum;

            int numProducts = await ProductDB.GetTotalProductsAsync(_context);

            int totalPages = (int)Math.Ceiling((double)numProducts / PageSize);

            ViewData["MaxPage"] = totalPages;


            //Async with Query Syntax
            List<Product> products =
                await ProductDB.GetProductsAsync(_context, PageSize, pageNum);

            // Send list of products to view to be displayed
            return View(products);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(Product p) // Use Async with DB code
        {
            if (ModelState.IsValid)
            {
                await ProductDB.AddProductAsync(_context, p);

                // last through one redirect
                TempData["Message"] = $"Your {p.Title} was added successfully!";

                // redirect to catalog page
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
           // Get product with corrisponding ID
           Product p = await ProductDB.GetSingleProductAsync(_context, id);

            // Pass product to view
            return View(p);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Product p)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(p).State = EntityState.Modified;
                await _context.SaveChangesAsync();

                // last through one redirect
                TempData["Message"] = $"Your {p.Title} has been edited!";

                // redirect to catalog page
                return RedirectToAction("Index");
            }

            return View(p);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Product p = await ProductDB.GetSingleProductAsync(_context, id);
            return View(p);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Product p = await ProductDB.GetSingleProductAsync(_context, id);

            _context.Entry(p).State = EntityState.Deleted;
            await _context.SaveChangesAsync();

            TempData["Message"] = $"Your {p.Title} has been deleted!";

            return RedirectToAction("Index");
        }
    }
}

eCommerceSite/Controllers/UserController.cs
using eCommerceSite.Data;
using eCommerceSite.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eCommerceSite.Controllers
{
    public class UserController : Controller
    {
        private readonly ProductContext _context;

        public UserController(ProductContext context)
        {
            _context = context;
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel reg)
        {
            if (ModelState.IsValid)
            {
                // Can refactor this later MAKE A ISSUE! delete this if you made the issue ^.^
                // Check if Email is unique
                bool isEmailTaken = await (from acc in _context.UserAccounts
                                           where acc.Email == reg.Email
                                           select acc).AnyAsync();

                // If email is not Unique error and send abck to view
                if (isEmailTaken)
                {
                    ModelState.AddModelError(nameof(RegisterViewModel.Email), "That email is already in use.");
                }

                // Check for Username
                bool isUsernameTaken = await (from acc in _context.UserAccounts
                                           where acc.UserName == reg.UserName
                                           select acc).AnyAsync();

                // If username is not Unique error and send abck to view
                if (isUsernameTaken)
                {
                    ModelState.AddModelError(nameof(RegisterViewModel.UserName), "That username is already in use.");
                }
                if (isEmailTaken || isUsernameTaken)
                {
                    return View(reg);
                }

                // Map Data to user account object !!This step is for ViewModels!!
                UserAccount account = new UserAccount()
                {
                    DateOfBirth = reg.DateOfBirth,
                    Email = reg.Email,
                    Password = reg.Password,
                    UserName = reg.UserName
                };
                // Add to database
                _context.UserAccounts.Add(account);
                await _context.SaveChangesAsync();

                // Log user in
                LogUserIn(account.UserID);

                // Say Hello!
                TempData["Message"] = $"Thank you for registering an account with us {reg.UserName}!";

                // Redirect to home
                return RedirectToAction("Index", "Home");
            }
            return View(reg);
        }

        public IActionResult Login()
        {
            // Check if user is already logged in
            if (HttpContext.Session.GetInt32("UserId").HasValue)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LogInViewModel logIn)
        {
            if (!ModelState.IsValid)
            {
                return View(logIn);
            }
            UserAccount account = await (from u in _context.UserAccounts
                                         where (u.UserName == logIn.UserNameOrEmail
                                             || u.Email == logIn.UserNameOrEmail)
                                         && u.Password == logIn.Password
                                         select u).SingleOrDefaultAsync();

            // Method syntax
            //UserAccount acc = await _context.UserAccounts
            //    .Where(userAcc => 
            //          (userAcc.UserName == logIn.UserNameOrEmail 
            //        || userAcc.Email == logIn.UserNameOrEmail)
            //        && userAcc.Password == logIn.Password).SingleOrDefaultAsync();

            if (account == null)
            {
                // Credentials did not match
                ModelState.AddModelError(nameof(LogInViewModel.UserNameOrEmail), "That account was not found please try again.");
                // Error Message
                TempData["Message"] = $"Im sorry your Login Information was not correct.";
                return View(logIn);
            }
            // Say Hello!
            TempData["Message"] = $"Welcome back {account.UserName}!";

            // Log User into website. Do this after adding sessions to start up.
            LogUserIn(account.UserID);

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Logout()
        {
            // Destroy Session
            HttpContext.Session.Clear();

            // Redirect to Homepage
            return RedirectToAction("Index", "Home");
        }

        private void LogUserIn(int accountId)
        {
            HttpContext.Session.SetInt32("UserId", accountId);
        }
    }
}

eCommerceSite/Views/Shared/_Layout.cshtml
@using Microsoft.EntityFrameworkCore
@*Using gets added to the ViewImports Page*@
@inject IHttpContextAccessor sessionData
@inject eCommerceSite.Data.ProductContext db
@{       
    int? userId = sessionData.HttpContext.Session.GetInt32("UserId");
    string userName = null;
    if (userId.HasValue)
    {
        string userNameFromSession = sessionData.HttpContext.Session.GetString("userName");
        if (userNameFromSession == null) // If userName is not in session put it in session to call DB only once
        {
            userName = await (from u in db.UserAccounts
                              where u.UserID == userId
                              select u.UserName).SingleOrDefaultAsync();

            sessionData.HttpContext.Session.SetString("userName", userName);
        }
        else
        {
            userName = userNameFromSession;
        }

    }

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eCommerceSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eCommerceSite</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="Index">Product Catalog</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-light" asp-area="" asp-controller="Cart" asp-action="Summary">

                                @{
                                    int total = CookieHelper.GetNumOFCartProducts(sessionData);
                                }
                                @if (total == 0)
                                {
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                                        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                                    </svg>
                                }
                                else
                                {
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-cart-fill" viewBox="0 0 16 16">
                                        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                                    </svg>
                                    @total
                                }
                            </a>
                        </li>

                        @if (userId == null) // If not logged in
                        {
                            <li class="nav-item ml-auto">
                                <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav.item ml-auto">
                                <a class="nav-link text-light disabled">@userName</a>
                            </li>
                            <li class="nav.item">
                                <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - eCommerceSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>